[package]
name = "metered-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
mongodb = "2.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
tokio = {version = "1.37.0", features = ["full"]}
toml = "0.8.12"
wither = "0.9.0"
